name: License Compliance Check

on: [push, pull_request]

jobs:
  license-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

    - name: Run License Compliance Checker
      uses: soheilbr82/automated-license-check@28445ce45ee4bcd5535e54e26d6c90cc7ae6aae1 # v1
      with:
        allowed_licenses: "MIT, Apache-2.0, BSD-3-Clause"
